"""chathistory

Revision ID: 0bb91a4d6ec5
Revises: 2f3b39ea89d5
Create Date: 2025-05-23 13:58:19.179588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0bb91a4d6ec5'
down_revision: Union[str, None] = '2f3b39ea89d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chathistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_message', sa.String(), nullable=False),
    sa.Column('bot_response', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chathistory_created'), 'chathistory', ['created'], unique=False)
    op.create_index(op.f('ix_chathistory_id'), 'chathistory', ['id'], unique=False)
    op.create_index(op.f('ix_chathistory_is_deleted'), 'chathistory', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_chathistory_modified'), 'chathistory', ['modified'], unique=False)
    op.alter_column('processedfile', 'result',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('processedfile', 'result',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_index(op.f('ix_chathistory_modified'), table_name='chathistory')
    op.drop_index(op.f('ix_chathistory_is_deleted'), table_name='chathistory')
    op.drop_index(op.f('ix_chathistory_id'), table_name='chathistory')
    op.drop_index(op.f('ix_chathistory_created'), table_name='chathistory')
    op.drop_table('chathistory')
    # ### end Alembic commands ###
