"""create user table

Revision ID: 5439773cff36
Revises: 389fa78c5b29
Create Date: 2025-04-29 16:28:13.890172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5439773cff36'
down_revision: Union[str, None] = '389fa78c5b29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inputfeature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('feature_name', sa.String(), nullable=True),
    sa.Column('feature_value', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inputfeature_created'), 'inputfeature', ['created'], unique=False)
    op.create_index(op.f('ix_inputfeature_id'), 'inputfeature', ['id'], unique=False)
    op.create_index(op.f('ix_inputfeature_is_deleted'), 'inputfeature', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_inputfeature_modified'), 'inputfeature', ['modified'], unique=False)
    op.create_index(op.f('ix_inputfeature_prediction_id'), 'inputfeature', ['prediction_id'], unique=False)
    op.create_table('modelversion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_name', sa.String(), nullable=False),
    sa.Column('model_file_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_name')
    )
    op.create_index(op.f('ix_modelversion_created'), 'modelversion', ['created'], unique=False)
    op.create_index(op.f('ix_modelversion_id'), 'modelversion', ['id'], unique=False)
    op.create_index(op.f('ix_modelversion_is_deleted'), 'modelversion', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_modelversion_modified'), 'modelversion', ['modified'], unique=False)
    op.create_table('requestlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('service_name', sa.Text(), nullable=True),
    sa.Column('processing_time', sa.Float(), nullable=True),
    sa.Column('tracker_id', sa.String(length=100), nullable=True),
    sa.Column('ip', sa.String(length=50), nullable=True),
    sa.Column('request', sa.Text(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('trace', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requestlog_created'), 'requestlog', ['created'], unique=False)
    op.create_index(op.f('ix_requestlog_is_deleted'), 'requestlog', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_requestlog_modified'), 'requestlog', ['modified'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_created'), 'user', ['created'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_is_deleted'), 'user', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_user_modified'), 'user', ['modified'], unique=False)
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    op.create_table('prediction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('prediction_result', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_created'), 'prediction', ['created'], unique=False)
    op.create_index(op.f('ix_prediction_id'), 'prediction', ['id'], unique=False)
    op.create_index(op.f('ix_prediction_is_deleted'), 'prediction', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_prediction_modified'), 'prediction', ['modified'], unique=False)
    op.create_index(op.f('ix_prediction_user_id'), 'prediction', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prediction_user_id'), table_name='prediction')
    op.drop_index(op.f('ix_prediction_modified'), table_name='prediction')
    op.drop_index(op.f('ix_prediction_is_deleted'), table_name='prediction')
    op.drop_index(op.f('ix_prediction_id'), table_name='prediction')
    op.drop_index(op.f('ix_prediction_created'), table_name='prediction')
    op.drop_table('prediction')
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.drop_index(op.f('ix_user_modified'), table_name='user')
    op.drop_index(op.f('ix_user_is_deleted'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_created'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_requestlog_modified'), table_name='requestlog')
    op.drop_index(op.f('ix_requestlog_is_deleted'), table_name='requestlog')
    op.drop_index(op.f('ix_requestlog_created'), table_name='requestlog')
    op.drop_table('requestlog')
    op.drop_index(op.f('ix_modelversion_modified'), table_name='modelversion')
    op.drop_index(op.f('ix_modelversion_is_deleted'), table_name='modelversion')
    op.drop_index(op.f('ix_modelversion_id'), table_name='modelversion')
    op.drop_index(op.f('ix_modelversion_created'), table_name='modelversion')
    op.drop_table('modelversion')
    op.drop_index(op.f('ix_inputfeature_prediction_id'), table_name='inputfeature')
    op.drop_index(op.f('ix_inputfeature_modified'), table_name='inputfeature')
    op.drop_index(op.f('ix_inputfeature_is_deleted'), table_name='inputfeature')
    op.drop_index(op.f('ix_inputfeature_id'), table_name='inputfeature')
    op.drop_index(op.f('ix_inputfeature_created'), table_name='inputfeature')
    op.drop_table('inputfeature')
    # ### end Alembic commands ###
