"""initial migration

Revision ID: 7b2b6e9b4a11
Revises: 27c3463bb804
Create Date: 2025-05-10 16:34:27.148771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b2b6e9b4a11'
down_revision: Union[str, None] = '27c3463bb804'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processedfile',
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_processedfile_created'), 'processedfile', ['created'], unique=False)
    op.create_index(op.f('ix_processedfile_is_deleted'), 'processedfile', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_processedfile_modified'), 'processedfile', ['modified'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processedfile_modified'), table_name='processedfile')
    op.drop_index(op.f('ix_processedfile_is_deleted'), table_name='processedfile')
    op.drop_index(op.f('ix_processedfile_created'), table_name='processedfile')
    op.drop_table('processedfile')
    # ### end Alembic commands ###
