"""improve

Revision ID: b3fcd4b9ff49
Revises: 7b2b6e9b4a11
Create Date: 2025-05-18 11:08:01.907765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3fcd4b9ff49'
down_revision: Union[str, None] = '7b2b6e9b4a11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modelversion', sa.Column('model_name', sa.String(), nullable=False))
    op.add_column('modelversion', sa.Column('framework', sa.String(), nullable=False))
    op.add_column('modelversion', sa.Column('inputs', sa.JSON(), nullable=False))
    op.add_column('modelversion', sa.Column('outputs', sa.JSON(), nullable=False))
    op.add_column('modelversion', sa.Column('preprocessing', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modelversion', 'preprocessing')
    op.drop_column('modelversion', 'outputs')
    op.drop_column('modelversion', 'inputs')
    op.drop_column('modelversion', 'framework')
    op.drop_column('modelversion', 'model_name')
    # ### end Alembic commands ###
