"""create user table

Revision ID: fd40ba373ac4
Revises: 5439773cff36
Create Date: 2025-04-29 16:34:14.046027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd40ba373ac4'
down_revision: Union[str, None] = '5439773cff36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=50), nullable=False))
    op.drop_column('user', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('full_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
